name: MicroHs CI

on:
  push:

# Using
#  runs-on: ubuntu-latest
# fails, so use an older Ubuntu

jobs:
  build-linux-emscripten:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - uses: mymindstorm/setup-emsdk@v13
     - uses: actions/setup-node@v4
       with:
         node-version: 20
     - name: run emscripten tests
       run: make runtestemscripten
