name: MicroHs CI

on:
  push:

# Using
#  runs-on: ubuntu-latest
# fails, so use an older Ubuntu

jobs:
  valgrind-compress-bwt:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: make
      run: make
    - name: valgrind
      run: |
        mhs Tmp.hs -o compress
        valgrind ./compress
